# Generated by Django 5.2.5 on 2025-09-03 08:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stockModel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('trade_code', models.CharField(max_length=10)),
                ('high_trade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('low_trade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('open_trade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_trade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('volume', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'db_table': 'stock_data',
                'ordering': ['-date', 'trade_code'],
                'indexes': [models.Index(fields=['trade_code'], name='stock_data_trade_c_244054_idx'), models.Index(fields=['date'], name='stock_data_date_56db21_idx'), models.Index(fields=['trade_code', 'date'], name='stock_data_trade_c_e4df7d_idx')],
            },
        ),
    ]
