# Generated by Django 5.2.5 on 2025-09-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_api', '0002_alter_stockmodel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmodel',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
